name: Docker Image CI

on:
  push:
    branches: [ "master", "0.1", "0.2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: schenkd/nginx-ui
          tag_with_ref: true
